SELECT
    TRIM(name) AS name,
    TRIM(type) AS type,
    TRIM(operator) AS operator,
    TRIM(brand) AS brand,
    TRIM(cuisine) AS cuisine,
    TRIM(vegetarian) AS vegetarian,
    TRIM(vegan) AS vegan,
    TRIM(opening_hours) AS opening_hours,
    TRIM(wheelchair) AS wheelchair,
    TRIM(delivery) AS delivery,
    TRIM(takeaway) AS takeaway,
    TRIM(drive_through) AS drive_through,
    TRIM(internet_access) AS internet_access,
    capacity,
    SAFE_CAST(stars AS FLOAT64) AS stars,
    TRIM(smoking) AS smoking,
    TRIM(wikidata) AS wikidata,
    TRIM(siret) AS siret,
    TRIM(phone) AS phone,
    TRIM(website) AS website,
    TRIM(facebook) AS facebook,
    TRIM(meta_name_com) AS meta_name_com,
    SAFE_CAST(meta_code_com AS INT64) AS meta_code_com,
    TRIM(meta_name_dep) AS meta_name_dep,
    SAFE_CAST(meta_code_dep AS INT64) AS meta_code_dep,
    TRIM(meta_name_reg) AS meta_name_reg,
    SAFE_CAST(meta_code_reg AS INT64) AS meta_code_reg,
    meta_geo_point AS meta_geo_point,
    SAFE_CAST(meta_osm_id AS INT64) AS meta_osm_id
FROM
    {{ source('raw', 'osm-france-food-service') }}