suretbon:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: marts
      threads: 1
      keyfile: "{{ env_var('GCP_SERVICE_ACCOUNT_KEY_JSON_FILEPATH') }}"